/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package function

import kotlin.test.Test
import kotlin.test.assertNotNull

class FnTest {
    @Test fun testFnSayHello() {
        val classUnderTest = Fn()
        assertNotNull(classUnderTest.hello("test"), "function should say hello")
    }
}